name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "eb01f29a79714857364120b513b2ec4343d95cf69f3a629ee29f84b6e9723cbe06-31986893-2c98-4a50-879b-d80add72589401026120b8de0b10"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "app/api"
          output_location: ".next"
          app_build_command: "npm run build"
          api_build_command: "npm run build" 